### ISSUE TITLE
FIR filter creates odd output with interpolation greater then 1

### ISSUE THREAD

**Issue by ashley-b** [pothosware/pothos-comms#28]
I noticed when creating a fractional fir filter (ie interpolation/decimation) the filter out is quite odd, I don't believe this is correct behaviour.
Also when I just have an integer value of n interpolation and decimation of 1 the filtered output is still not what I would expect.
![FIR filter Issue](https://user-images.githubusercontent.com/5248379/56457290-bd736000-63bb-11e9-8caf-5fdee7dbda6b.png)

Thanks

**Comment by guruofquality** [comment]
Oh, its basically interpolation filtering the decimated samples, hence the aliases.

**Comment by ashley-b** [comment]
I try the new branch and the aliases seams to be fixed.
I did notice that I need to scale the Sample Rate of the FIR Designer by the interpolation value to give the correct cut of frequency, just wondering if this is correct behaviour.

**Comment by guruofquality** [comment]
When interpolating, the cut off in the fir designer refers to the output rate. When decimating the cut off in the fir designer refers to the input rate. So when you have both interpolation and decimation, which looks like something this block did not do well simultaneously before, the cut-off essentially applies to the intermediate higher rate post interpolation but before the decimation. I'm not entirely sure I like that, Ideally it would be relative to the input always -- but since the designer is decoupled from the filter block, the interpolation taps would have to be changed in some way.
